In [1]:
import _resume_eval_import_helper

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("output/two_stage_evaluation_results_detailed.csv")

df_yes = df[df["suitability"] == "yes"].reset_index(drop=True)
df_potential = df[df["suitability"] == "kiv"].reset_index(drop=True)

del df

In [7]:
df_yes.sort_values(["job_id", "recalibrated_overall_score"])

,job_id,cv_id,model_name,original_technical_skills,original_soft_skills,original_experience,original_education,recalibrated_technical_skills,recalibrated_soft_skills,recalibrated_experience,...,inferred_experience,suitability,strengths,concerns,original_overall_score,recalibrated_overall_score,job_title,job_description,cv_category,cv
7,40705682-6752-41f0-8a6d-b01b9d7b1746,af844c8b-de2a-47ff-9b7d-4466af8826c2,groq,80,80,70,100,85,85,75,...,"Data Science, Machine Learning, Natural Langua...",yes,The candidate has strong technical skills in P...,"The candidate lacks experience with Django, wh...",80.0,84.5,Backend Developer,Job Summary -\nLumenci is a legal tech startup...,Data Science,Skills * Programming Languages: Python (pandas...
2,5535b3b6-f919-4e04-bb23-5eb63436941f,86cab53a-a56e-46a5-a788-ed9ce55b6879,groq,80,90,70,80,85,95,75,...,"Database development, Client interaction",yes,"The candidate has excellent technical skills, ...","The candidate lacks experience in DB modeling,...",79.0,83.5,Database Administrator,mandatory skill rdbms - database development j...,Database,"TECHNICAL SKILLS SQL Oracle v10, v11, v12 R..."
0,5535b3b6-f919-4e04-bb23-5eb63436941f,b2787176-a5e0-45be-affa-6f955925ddc6,groq,80,60,80,100,85,65,85,...,Experience with distributed processing algorit...,yes,The candidate has strong technical skills in H...,"The candidate lacks experience in DB modeling,...",80.0,84.5,Database Administrator,mandatory skill rdbms - database development j...,Hadoop,Education Details \nHadoop Developer \nHadoop ...
3,5535b3b6-f919-4e04-bb23-5eb63436941f,bd1a92a0-5f5a-4b88-b3e2-606f9c10fbd1,groq,80,70,90,80,85,75,95,...,"Database development, RDBMS",yes,The candidate has strong technical skills in O...,"The candidate lacks experience in DB modeling,...",81.0,85.5,Database Administrator,mandatory skill rdbms - database development j...,Database,TECHNICAL EXPERTISE DB Languages: SQL Databa...
9,5535b3b6-f919-4e04-bb23-5eb63436941f,a475d257-1db0-4073-a2e7-c102b5440dc5,groq,80,60,90,100,85,70,95,...,"leadership skill, agile environment experience",yes,The candidate has extensive experience in data...,"The candidate lacks experience in DB modeling,...",82.0,87.0,Database Administrator,mandatory skill rdbms - database development j...,Database,TECHNICAL SKILLS Operating Systems MS Windows ...
4,5535b3b6-f919-4e04-bb23-5eb63436941f,954ab12a-1f45-46fb-b96c-4bb8d8f6d59f,groq,80,90,90,100,85,95,95,...,"leadership skills, project management skills, ...",yes,The candidate has extensive experience in SAP ...,"The candidate lacks experience in RDBMS, Datab...",85.0,89.5,Database Administrator,mandatory skill rdbms - database development j...,SAP Developer,Education Details \nSAP Technical Architect \n...
5,5535b3b6-f919-4e04-bb23-5eb63436941f,8ebd43dc-8000-4c15-baad-1868b349ea56,groq,90,60,80,80,95,70,90,...,"Database development, RDBMS",yes,The candidate has strong technical skills in O...,"The candidate lacks experience in DB modeling,...",84.0,90.0,Database Administrator,mandatory skill rdbms - database development j...,Database,Education Details \nMay 2011 to May 2014 Bache...
6,769c3093-32c5-4122-ae8f-d4f99a22354a,39b5761c-b124-4c97-86a1-9f3ef0d5b77c,groq,80,60,70,100,85,65,75,...,"Full Stack Development, Cloud Computing",yes,"Strong technical skills, particularly in MEAN ...","Lack of experience in MERN Stack, which is an ...",78.0,82.5,JavaScript Developer,"MEAN / MERN Stack Developer , 1 yr of experien...",Blockchain,Skills Strong CS fundamentals and problem solv...
8,b04cc5ce-b93e-427e-9439-0965e64779ff,797436e9-bd0e-42f1-85fe-1fd288a575fc,groq,80,60,90,80,85,70,95,...,"Project management skills, Team leadership ski...",yes,"The candidate has strong technical skills, par...",The candidate lacks experience in MVC design p...,80.0,85.0,PHP Developer,"We, Techvoot Solutions are urgent hiring PHP L...",DevOps Engineer,Total IT Experience 15 years. Core expertise i...
1,ca0539ba-835b-48fb-bed0-705d6668c372,21124c0b-1510-481b-b006-7bf6bebec2a0,groq,80,60,70,80,85,70,75,...,"leadership, teamwork",yes,"The candidate has strong technical skills, par...",The candidate lacks experience with VB.NET and...,76.0,81.0,Java Developer,Solar Innovations is an Equal Opportunity Empl...,DotNet Developer,"Technical Skills Languages: C#, ASP .NET MVC,..."

In [9]:
df_yes[df_yes["job_id"] == "40705682-6752-41f0-8a6d-b01b9d7b1746"].T

                                                                               7
job_id                                      40705682-6752-41f0-8a6d-b01b9d7b1746
cv_id                                       af844c8b-de2a-47ff-9b7d-4466af8826c2
model_name                                                                  groq
original_technical_skills                                                     80
original_soft_skills                                                          80
original_experience                                                           70
original_education                                                           100
recalibrated_technical_skills                                                 85
recalibrated_soft_skills                                                      85
recalibrated_experience                                                       75
recalibrated_education                                                       100
inferred_experience            Data Science, Machine Learning, Natural Langua...
suitability                                                                  yes
strengths                      The candidate has strong technical skills in P...
concerns                       The candidate lacks experience with Django, wh...
original_overall_score                                                      80.0
recalibrated_overall_score                                                  84.5
job_title                                                      Backend Developer
job_description                Job Summary -\nLumenci is a legal tech startup...
cv_category                                                         Data Science
cv                             Skills * Programming Languages: Python (pandas...

In [11]:
print(df_yes[df_yes["job_id"] == "40705682-6752-41f0-8a6d-b01b9d7b1746"]["job_description"].values[0])

Job Summary -
Lumenci is a legal tech startup founded by group of IIT alumni in US. Lumenci’s mission is to transform the legal and intellectual property industry in US & Europe with groundbreaking products and services. We are currently looking to build an exceptionally strong technical team in Gurgaon, India, to help us deliver high quality products and services to our clients.
The Role
 Design and develop software tools related to tracking, implementing, managing and presenting data.
 Researching, designing, implementing and managing software programs
 Testing and evaluating new programs
 Identifying areas for modification in existing programs and subsequently developing these modifications
 Writing and implementing efficient code
 Determining operational practicality
 Develop software tools which will automate various manual processes.
 Develop and design dashboard and UI related tools.
 Build, optimize, and maintain an easy-to-use, powerful web application.
 Deliver reliable software through continuous integration, automated testing, and in-depth code reviews.
 Work on a fast-moving team that delivers on shared commitments.
 Work closely with technical consultant, designers, other developers
Must have
 Bachelor’s degree or equivalent in Computer Science or Engineering.
 Strong experience in programming language such as Python v3.6.6
 Strong experience in framework such as Django.
 Critical thinking and problem-solving skills.
 Good interpersonal and communication skills.
Benefits
 Competitive stock option plan at end of Year 2
 Rapid career growth as the Company expands
Job Type: Full-time
Salary: ₹700,000.00 - ₹1,000,000.00 per year
Schedule:
Monday to Friday
Experience:
Back End Developer: 3 years (Preferred)
Education:
Bachelor's (Preferred)
Location:
Gurgaon, Haryana (Preferred)
Work Remotely:
Temporarily due to COVID-19

In [12]:
print(df_yes[df_yes["job_id"] == "40705682-6752-41f0-8a6d-b01b9d7b1746"]["cv"].values[0])

Skills * Programming Languages: Python (pandas, numpy, scipy, scikit-learn, matplotlib), Sql, Java, JavaScript/JQuery. * Machine learning: Regression, SVM, Nave Bayes, KNN, Random Forest, Decision Trees, Boosting techniques, Cluster Analysis, Word Embedding, Sentiment Analysis, Natural Language processing, Dimensionality reduction, Topic Modelling (LDA, NMF), PCA & Neural Nets. * Database Visualizations: Mysql, SqlServer, Cassandra, Hbase, ElasticSearch D3.js, DC.js, Plotly, kibana, matplotlib, ggplot, Tableau. * Others: Regular Expression, HTML, CSS, Angular 6, Logstash, Kafka, Python Flask, Git, Docker, computer vision - Open CV and understanding of Deep learning.Education Details
Data Science Assurance Associate
Data Science Assurance Associate - Ernst & Young LLP
Skill Details
JAVASCRIPT- Exprience - 24 months
jQuery- Exprience - 24 months
Python- Exprience - 24 monthsCompany Details
company - Ernst & Young LLP
description - Fraud Investigations and Dispute Services   Assurance
TECHNOLOGY ASSISTED REVIEW
TAR (Technology Assisted Review) assists in accelerating the review process and run analytics and generate reports.
* Core member of a team helped in developing automated review platform tool from scratch for assisting E discovery domain, this tool implements predictive coding and topic modelling by automating reviews, resulting in reduced labor costs and time spent during the lawyers review.
* Understand the end to end flow of the solution, doing research and development for classification models, predictive analysis and mining of the information present in text data. Worked on analyzing the outputs and precision monitoring for the entire tool.
* TAR assists in predictive coding, topic modelling from the evidence by following EY standards. Developed the classifier models in order to identify "red flags" and fraud-related issues.
Tools & Technologies: Python, scikit-learn, tfidf, word2vec, doc2vec, cosine similarity, Nave Bayes, LDA, NMF for topic modelling, Vader and text blob for sentiment analysis. Matplot lib, Tableau dashboard for reporting.
MULTIPLE DATA SCIENCE AND ANALYTIC PROJECTS (USA CLIENTS)
TEXT ANALYTICS - MOTOR VEHICLE CUSTOMER REVIEW DATA * Received customer feedback survey data for past one year. Performed sentiment (Positive, Negative & Neutral) and time series analysis on customer comments across all 4 categories.
* Created heat map of terms by survey category based on frequency of words * Extracted Positive and Negative words across all the Survey categories and plotted Word cloud.
* Created customized tableau dashboards for effective reporting and visualizations.
CHATBOT * Developed a user friendly chatbot for one of our Products which handle simple questions about hours of operation, reservation options and so on.
* This chat bot serves entire product related questions. Giving overview of tool via QA platform and also give recommendation responses so that user question to build chain of relevant answer.
* This too has intelligence to build the pipeline of questions as per user requirement and asks the relevant /recommended questions.
Tools & Technologies: Python, Natural language processing, NLTK, spacy, topic modelling, Sentiment analysis, Word Embedding, scikit-learn, JavaScript/JQuery, SqlServer
INFORMATION GOVERNANCE
Organizations to make informed decisions about all of the information they store. The integrated Information Governance portfolio synthesizes intelligence across unstructured data sources and facilitates action to ensure organizations are best positioned to counter information risk.
* Scan data from multiple sources of formats and parse different file formats, extract Meta data information, push results for indexing elastic search and created customized, interactive dashboards using kibana.
* Preforming ROT Analysis on the data which give information of data which helps identify content that is either Redundant, Outdated, or Trivial.
* Preforming full-text search analysis on elastic search with predefined methods which can tag as (PII) personally identifiable information (social security numbers, addresses, names, etc.) which frequently targeted during cyber-attacks.
Tools & Technologies: Python, Flask, Elastic Search, Kibana
FRAUD ANALYTIC PLATFORM
Fraud Analytics and investigative platform to review all red flag cases.
 FAP is a Fraud Analytics and investigative platform with inbuilt case manager and suite of Analytics for various ERP systems.
* It can be used by clients to interrogate their Accounting systems for identifying the anomalies which can be indicators of fraud by running advanced analytics
Tools & Technologies: HTML, JavaScript, SqlServer, JQuery, CSS, Bootstrap, Node.js, D3.js, DC.js

In [13]:
print(df_yes[df_yes["job_id"] == "40705682-6752-41f0-8a6d-b01b9d7b1746"]["concerns"].values[0])

The candidate lacks experience with Django, which is an essential skill for the job. However, their overall skills and experience make them a strong fit for the role.

In [14]:
# 5535b3b6-f919-4e04-bb23-5eb63436941f

In [17]:
df_yes[df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f"].T

,0,2,3,4,5,9
job_id,5535b3b6-f919-4e04-bb23-5eb63436941f,5535b3b6-f919-4e04-bb23-5eb63436941f,5535b3b6-f919-4e04-bb23-5eb63436941f,5535b3b6-f919-4e04-bb23-5eb63436941f,5535b3b6-f919-4e04-bb23-5eb63436941f,5535b3b6-f919-4e04-bb23-5eb63436941f
cv_id,b2787176-a5e0-45be-affa-6f955925ddc6,86cab53a-a56e-46a5-a788-ed9ce55b6879,bd1a92a0-5f5a-4b88-b3e2-606f9c10fbd1,954ab12a-1f45-46fb-b96c-4bb8d8f6d59f,8ebd43dc-8000-4c15-baad-1868b349ea56,a475d257-1db0-4073-a2e7-c102b5440dc5
model_name,groq,groq,groq,groq,groq,groq
original_technical_skills,80,80,80,80,90,80
original_soft_skills,60,90,70,90,60,60
original_experience,80,70,90,90,80,90
original_education,100,80,80,100,80,100
recalibrated_technical_skills,85,85,85,85,95,85
recalibrated_soft_skills,65,95,75,95,70,70
recalibrated_experience,85,75,95,95,90,95
recalibrated_education,100,80,80,100,80,100
inferred_experience,Experience with distributed processing algorit...,"Database development, Client interaction","Database development, RDBMS","leadership skills, project management skills, ...","Database development, RDBMS","leadership skill, agile environment experience"
suitability,yes,yes,yes,yes,yes,yes
strengths,The candidate has strong technical skills in H...,"The candidate has excellent technical skills, ...",The candidate has strong technical skills in O...,The candidate has extensive experience in SAP ...,The candidate has strong technical skills in O...,The candidate has extensive experience in data...
concerns,"The candidate lacks experience in DB modeling,...","The candidate lacks experience in DB modeling,...","The candidate lacks experience in DB modeling,...","The candidate lacks experience in RDBMS, Datab...","The candidate lacks experience in DB modeling,...","The candidate lacks experience in DB modeling,..."
original_overall_score,80.0,79.0,81.0,85.0,84.0,82.0
recalibrated_overall_score,84.5,83.5,85.5,89.5,90.0,87.0
job_title,Database Administrator,Database Administrator,Database Administrator,Database Administrator,Database Administrator,Database Administrator
job_description,mandatory skill rdbms - database development j...,mandatory skill rdbms - database development j...,mandatory skill rdbms - database development j...,mandatory skill rdbms - database development j...,mandatory skill rdbms - database development j...,mandatory skill rdbms - database development j...
cv_category,Hadoop,Database,Database,SAP Developer,Database,Database
cv,Education Details \nHadoop Developer \nHadoop ...,"TECHNICAL SKILLS SQL Oracle v10, v11, v12 R...",TECHNICAL EXPERTISE DB Languages: SQL Databa...,Education Details \nSAP Technical Architect \n...,Education Details \nMay 2011 to May 2014 Bache...,TECHNICAL SKILLS Operating Systems MS Windows ...

In [23]:
from pprint import pprint

pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "8ebd43dc-8000-4c15-baad-1868b349ea56")]["cv"].values[0])

('Education Details \n'
 'May 2011 to May 2014 Bachelor of science Information technology Mumbai, '
 'Maharashtra Mumbai university\n'
 'Oracle DBA \n'
 'Oracle database administrator\n'
 'Skill Details \n'
 'Installation of Oracle on RH Linux & Windows. Creating/Managing user '
 'profiles and analyzing their privileges and tablespace quotas Backup of '
 'database Logical and Physical procedures. Recovery of database in case of '
 'database crash, disk/media failure, etc. Standard DBA functions like space '
 'management, Rollback segments, Extents. Database Management and Monitoring '
 'the database. Willing to learn new things. Being a constructive team member, '
 'contributing practically to the success of the team.- Exprience - 48 '
 'monthsCompany Details \n'
 'company - Accelya kale solutions ltd\n'
 'description - Database Administrator working in 24*7 support environment '
 'maintaining Databases running on Oracle 11g, 12c.\n'
 'Database Up-gradation from Oracle 11g to Oracle 12c.\n'
 'Installation of Database critical patches.\n'
 'Taking cold and hot backups on scheduled times and monitoring backups.\n'
 'Importing the export dump to another database as per demands.\n'
 'Automating most of the daily activities through cronjobs, shell scripts or '
 'schedulers.\n'
 'Making Plan of Actions for Various Activities.\n'
 'Raising SR with Oracle Support for different severity issues.\n'
 'Handling the Users request and proper client interaction.\n'
 'Monitoring & managing database growth, tablespaces, adding ,resizing and '
 'renaming the datafiles.\n'
 'Restoration of database using RMAN backups for backup consistency checks.\n'
 'Migration of Database using export / import and RMAN backups.\n'
 'Configuring & managing Physical Standby database.\n'
 'Creating database links, Tablespaces, database directories.\n'
 'Managing network settings through listener.ora and tnsnames.ora files.\n'
 'Restoration of data using old logical backup as per client request.\n'
 'Schema replication across databases through data pump tool.\n'
 'Taking cold and hot backups on scheduled times and monitoring backups\n'
 'Taking EXPDP of database, database objects and a particular schema\n'
 'Using SCP ticketing tool in order keeping track of client requests.\n'
 'Performing Maintenance Activities such as Index Rebuilding and stats '
 'gather.\n'
 'Troubleshooting the Basic Levelperformance issues\n'
 'Setting up a new environmentfrom database perspective within the requested '
 'timelines\n'
 'Adding/Deleting disks in ASM and monitoring the ASM diskgroups.\n'
 'Creating users & privileges with appropriate roles and levels of security.\n'
 'Database Administrator working in 24*7 support environment maintaining '
 'Databases running on Oracle 11g, 12c.\n'
 'Performing database online and offline database re-organization for database '
 'enhancement.\n'
 'Migrating database from Non-ASM to ASM file system.\n'
 'Grid up-gradation from 11g to 12C.\n'
 'company - Insolutions Global Ltd\n'
 'description - Oracle software installation(graphical/silent),Database '
 'upgrade,Patch upgrade.\n'
 'Maintaining around 80+ UAT DB servers, 40 production DB and 28 standby/DR '
 'DB.\n'
 'Managing/creating DR & standby servers, DB sync.\n'
 'Backup and recovery (RMAN/ Datapump).\n'
 'Performing activities like switchover and failover .\n'
 'Allocating system storage and planning future storage requirements for the '
 'database system\n'
 'Enrolling users and maintaining system security.\n'
 'Monitoring Alert log, Snap ID generation, db size, Server space, OEM '
 'reports, User validity.\n'
 'Controlling and monitoring user access to the database .\n'
 'Scheduling shell scripts or dbms_jobs using Crontab or DBMS_SCHEDULER '
 '(monitoring script, listener check, backup script, AWR reports) etc.\n'
 'Planning for backup and recovery of database.\n'
 'Managing the production database for Oracle and SQL Server and resize the '
 'space of database/Datafiles/Tablespace/Transactional Logs.\n'
 'Managing Temp and Undo tablespaces.\n'
 'Creating primary database storage structures (tablespaces) after application '
 'developers have designed an application.')

In [26]:
pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "8ebd43dc-8000-4c15-baad-1868b349ea56")]["job_description"].values[0])

('mandatory skill rdbms - database development job description key skill '
 'required job rdbms - database development-l3 mandatory minimum work '
 'experience:7 - 10 year 7-10 year experience good background experience data '
 'analysis experience gathering analyzing system requirement able formulate '
 'quick data analysis agile environment contribute design implementation '
 'perspective business need strong experience source target mapping excellent '
 'communication skill exposure client interaction day day basis excellent '
 'leadership skill drive agile based project development good knowledge sql '
 'oracle good understanding data model database design principle experience '
 'agile development process ba/da experience requirement design documentation '
 'role & responsibility minimum experience required 3-5 year mandatory skill '
 'rdbms - database development db modeling unix shell scripting perl '
 'programming rdbms - database development desirable skill language skill '
 'english language')

In [24]:

pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "8ebd43dc-8000-4c15-baad-1868b349ea56")]["concerns"].values[0])

('The candidate lacks experience in DB modeling, Unix shell scripting, and '
 'Perl programming, which are essential skills for the job.')

In [25]:
pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "8ebd43dc-8000-4c15-baad-1868b349ea56")]["strengths"].values[0])

('The candidate has strong technical skills in Oracle DBA, database '
 'administration, and backup and recovery. They also have excellent experience '
 'in managing databases and performing maintenance activities.')

## case II

In [27]:
pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "954ab12a-1f45-46fb-b96c-4bb8d8f6d59f")]["cv"].values[0])

('Education Details \n'
 'SAP Technical Architect \n'
 'SAP Technical Consultant -  (ALE/IDOC/oDATA/Fiori/S4HANA/EWM/APO/Retail)\n'
 'Skill Details \n'
 'SAP ABAP- Exprience - 120 months\n'
 'SAP ABAP ( ALE / IDOC / EDI )- Exprience - 96 months\n'
 'SAP Netweaver Gateway / oData / Fiori- Exprience - 24 months\n'
 'SAP Techno Functional- Exprience - 36 months\n'
 'SAP ABAP ( IS-Retail / APO / IS-Auto / EWM)- Exprience - 36 months\n'
 'SAP Techno-functional- Exprience - 48 months\n'
 'SAP SD- Exprience - 36 months\n'
 'NetWeaver Gateway (oDATA, Fiori)- Exprience - 24 months\n'
 'SAP S/4HANA (new features Extensibility, Embedded Analytics)- Exprience - 12 '
 'monthsCompany Details \n'
 'company - \n'
 'description - 13+ years of work experience in SAP which includes roles '
 'varies from developer to subject matter expert\n'
 ' Strong project experience in implementation, upgrade, application '
 'development and maintenance\n'
 ' SAP ABAP Certified associate and has certification in ITIL 2011 Foundation '
 'and PRINCE2 practitioner\n'
 ' SAP project Full-Lifecycle implementations across multiple global projects\n'
 ' Direct client exposure of 1.3 years in United States of America and 1.2 '
 'years in Malaysia\n'
 ' Expertise on SAP ABAP FRICEW components\n'
 ' Experience in various SAP modules like MM, FI, CO, SD, PS, PP, CS, PM, QM '
 'and HR\n'
 ' Experience on S/4HANA, IS-Auto, IS-Retail, SCM 7.0, SOLMAN, SAP GTS, SAP PI '
 '7.3, SAP BI 7.0/ 7.3, Vistex, ProShip, HPQC, IBM ManageNow, CA service desk, '
 'Loftware, Data Matrix\n'
 ' Experience in SAP Netweaver Gateway (Fiori) and also created number of POCs '
 'for potential customers\n'
 ' Successfully completed 9 implementation, 7 support, 1 roll-out, and 1 '
 'upgrade projects\n'
 ' Expertise in understanding different requirements of the client for diverse '
 'industries\n'
 ' Experience in leading technical team of different sizes\n'
 ' Customization experience in various areas of SD, FI & MM modules\n'
 ' Experience in Upgrading to ECC6.0\n'
 ' Experience in Unicode conversion related issues/tasks.\n'
 ' Skilled in document processes, identifying issues, handling multiple tasks, '
 'and training end users.\n'
 ' Proven ability to interact with business system analysts and end-users in '
 'design phase\n'
 ' Extensive experience in analyzing complicated business processes, effort '
 'estimations and creating technical specifications.\n'
 ' Experienced with onsite-offshore support model of work and lead the team\n'
 ' Excellent communication skills, team participation, inter-team '
 'co-ordination, team leadership abilities and customer oriented attitude\n'
 ' Experience in pre-sales activities\n'
 ' Thorough understanding of the project management and quality processes')

In [28]:
pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "954ab12a-1f45-46fb-b96c-4bb8d8f6d59f")]["strengths"].values[0])

('The candidate has extensive experience in SAP ABAP and has worked on '
 'multiple projects, demonstrating strong technical skills. The candidate also '
 'has excellent communication skills, leadership skills, and experience in '
 'client interaction.')

In [29]:
pprint(df_yes[(df_yes["job_id"] == "5535b3b6-f919-4e04-bb23-5eb63436941f") & (df_yes["cv_id"] == "954ab12a-1f45-46fb-b96c-4bb8d8f6d59f")]["concerns"].values[0])

('The candidate lacks experience in RDBMS, Database development, Unix shell '
 'scripting, Perl programming, and DB modeling, which are essential skills for '
 'the job.')